bin/gm2table, gmprocess/io/fdsn.py, gmprocess/io/smc/core.py, gmprocess/stream.py, tests/bin/gm2table_test.py, tests/gmprocess/stream_test.py
Checked for nan values in group_channels and updated it to raise an
exception if streams with more than 3 channels are created.
Undefined hdr variable replaced with stats in smc reader removed.
Dataframe creation is possible by directory or set of streams.
Lat/lon bug in streams_to_dataframe fixed.
closes #26
closes #24 
closes #18 The nan values came from a bug in fdsn.py, but checks are now included in group_channels.
=> Addressing issues and bug fixes.

gmprocess/config.py, tests/gmprocess/config_test.py
Added merge_dict() to config.py for merging config information across multiple files.
config.get_config() still needs to be rewritten to use multiple config files (should be separate PR).
=> Implement functions to merge dictionaries (for merging config informatin).

gmprocess/corner_frequencies.py, gmprocess/pretesting.py, gmprocess/processing.py, gmprocess/stationstream.py, gmprocess/stationtrace.py, gmprocess/streamcollection.py, tests/gmprocess/processing_test.py, tests/gmprocess/streamcollection_test.py
Closes #76 
Closes #91 
Closes #109 
Closes #110
=> Updates to StreamCollection

gmprocess/io/test_utils.py, gmprocess/stream.py, gmprocess/streamcollection.py, tests/gmprocess/streamcollection_test.py
This will help get the amptools package to be better integrated with the recent changes in gmprocess.
=> Added to_dataframe method for StreamCollection and added tests

gmprocess/io/read_directory.py, tests/gmprocess/io/read_directory_test.py, tests/gmprocess/streamcollection_test.py
I think it may not be expected or desirable for these functions to actually modify the data locally and so I think this is safer.
=> Changed directory_to_streams to use temp dir

bin/datafetch, gmprocess/io/geonet/geonet_fetcher.py, gmprocess/io/global_fetcher.py, gmprocess/io/knet/core.py, gmprocess/io/knet/knet_fetcher.py, gmprocess/io/nsmn/core.py, gmprocess/io/nsmn/turkey_fetcher.py, gmprocess/pretesting.py, gmprocess/stationtrace.py, tests/gmprocess/io/global_data_fetcher_test.py
- Added datafetch tool and supporting fetch_data function
- Modified knet, geonet, nsmn readers as necessary
- Fixed bug in prechecks
- Added free-field checker in StationTrace (this needs more work).
=> Fixing help and event info inputs.

gmprocess/corner_frequencies.py, gmprocess/data/config.yml, gmprocess/plot.py
- Added a new plotting method for showing SNR stuff (see example attached). Whether or not plots should be made, as well as the directory can be specified in the config, or directly when calling the function.
- Fixed a bug in SNR where low corners and high corners were being swapped incorrectly in the case that the SNR is greater than threshold at the lowest frequency.
- Modified SNR failure reasons to be more specific.
- SNR now does a check to make sure signal and noise windows are not empty.
Todo/extensions:
- Fix provenance and parameters tables to be readable, possibly adjusting the row height or fontsize.
- Add magnitude/distance to parameters table
- Add theoretical spectrum/corner frequencies to plots.
- Create pdfs instead of saving individual png files
=> Adding SNR plotting.

bin/datafetch, gmprocess/io/asdf/stream_workspace.py, gmprocess/io/fetcher.py, gmprocess/io/geonet/geonet_fetcher.py, gmprocess/io/global_fetcher.py, gmprocess/io/knet/knet_fetcher.py, gmprocess/io/nsmn/turkey_fetcher.py, gmprocess/stationtrace.py, gmprocess/streamcollection.py, install.sh, tests/gmprocess/io/asdf/stream_workspace_test.py
- datafetch:
- organized output directories
- simplified command line arguments
- unhacked free-field dropper
- workspace:
- provenance documents are now unique to each Trace
- getProvenance method implemented, returns DataFrame
- Fetchers:
- All classes involved have drop_non_free option
- StationTrace:
- Added getProvSeries() method
- StreamCollection:
- now has drop_non_free in constructor
- install script now handling __pycache__ issue.
=> Fixed issues with datafetchers, workspace, non-free-field data.

gmprocess/plot.py, gmprocess/report.py
Layout improved reports/plots. Added velocity plots.
=> Report updates

docs/figs/palettes/palette_general.tex, docs/figs/palettes/palette_mmi.tex, docs/figs/palettes/palette_usgs.tex, docs/figs/palettes/view_colors.tex
Add missing color definition files for tikz figures in documentation.
=> Add missing color palette files for documentation.

gmprocess/plot.py, gmprocess/spectrum.py
- Fixes issue where rms variable in `fit_spectra` would contain all NaN values
- Summary plots should now be able to handle streams with 1 or 2 traces.
=> Theoretical spectrum and summary plot fixes

gmprocess/corner_frequencies.py, gmprocess/plot.py
Bug was that SNR couldn't be calculated but the results were trying to be accessed, raising an exception.
Also, I added magnitude to the summary plot titles.
=> Fixed snr bug

bin/datafetch, gmprocess/io/bhrc/core.py, gmprocess/io/cosmos/core.py, gmprocess/io/cwb/core.py, gmprocess/io/dmg/core.py, gmprocess/io/fdsn/core.py, gmprocess/io/geonet/core.py, gmprocess/io/knet/core.py, gmprocess/io/nsmn/core.py, gmprocess/io/read_directory.py, gmprocess/io/smc/core.py, gmprocess/io/usc/core.py, gmprocess/stationstream.py, gmprocess/stationtrace.py, gmprocess/streamcollection.py, tests/gmprocess/io/nsmn/nsmn_test.py
- add some debug logging
- add some more progress/status output to datfetch
- hard code USC file format to return negative longitudes
- added file name to stats dict
- delete orphaned methods that is never called in the nsmn reader. 
- bugfixs in datafetch for when a directory doesn't exist
Note: `datafetch` **now completes when given the CESMD data directory for Northridge!!**
=> Commit to rebase with recent changes

bin/datafetch, bin/gminfo, gmprocess/data/config.yml, gmprocess/io/dmg/core.py, gmprocess/io/usc/core.py, gmprocess/report.py, tests/gmprocess/io/asdf/stream_workspace_test.py
- added error catching for plotting raw data
- handle incorrectly specified npts in dmg header
- turn off baseline correction in default processing steps; probably should be an 'opt-in' step
- fixed bug where reserved values for horizontal orientation (i.e., not an angle) is getting preserved; this change required modifying tests
=> Misc bug fixes and tweaks

bin/gmprocess
=> Add config file to output directory

bin/gmprocess, gmprocess/io/cosmos/core.py, gmprocess/processing.py, gmprocess/snr.py, gmprocess/stationstream.py, gmprocess/streamcollection.py
- Bugfix for computing snr
- Better handling of COSMOS orientation errors 
- Validate that channel codes are not identical for different channels at a given station
- Added n_passed and n_failed as StationStream properties so that we can easily check that there are passed streams in places where it would only make sense to proceed if this is the case
- Modified gmprocess to exist more gracefully if no streams pass checks
- Cast header values as appropriate types where possible
=> Misc bugfixes

bin/gmprocess, gmprocess/report.py
- Add check for presence of input directory
- Fixed origin/event handling in build_report
=> Misc updates

bin/gmprocess, gmprocess/io/asdf/stream_workspace.py, gmprocess/metrics/station_summary.py, gmprocess/streamcollection.py, tests/gmprocess/io/asdf/stream_workspace_test.py
Cleaned up the way stream metrics (imc/imt values) are stored and handled in the ASDF workspace.
=> Metricsfix

gmprocess/adjust_highpass.py, gmprocess/corner_frequencies.py, gmprocess/data/config.yml, gmprocess/filtering.py, gmprocess/processing.py
- Initial implementation of some of the displacement checks, as described by Dawood et al. (2015) in adjust_highpass.py
- Moved filtering method to a dedicated module (was in processing.py)
- Method is currently commented out in default config because it needs to be tested
Closes #250
=> Displacement checks

docs/_config.yml, docs/_includes/nav.html
Need to set baseurl in docs/_config.yml and use baseurl in navigation bar so links are relative to the baseurl (usgs.github.io/groundmotion-processing).
=> Use baseurl in navbar links.

gmprocess/config.py, gmprocess/event.py, gmprocess/io/fdsn/fdsn_fetcher.py, gmprocess/io/fetcher.py, gmprocess/io/global_fetcher.py, gmprocess/logging.py, gmprocess/metrics/metrics_controller.py, gmprocess/phase.py, gmprocess/plot.py, gmprocess/report.py, gmprocess/stationtrace.py, gmprocess/stream.py, gmprocess/windows.py, setup.py
- Misc lint cleanup
- Tweaks to the report to include station/instrument info on each page; created a title page the embeds the station map; made the prov tables smaller to avoid jumping to next page (though I wish there was a better solution)
=> Linting and summary reports

gmprocess/nn_quality_assurance.py
=> Docstrings nn_qa

bin/gmprocess2, bin/list_metrics, gmprocess/data/testdata/gmprocess2_custom_config.yml, gmprocess/io/asdf/stream_workspace.py, gmprocess/io/fdsn/core.py, gmprocess/io/fetch_utils.py, gmprocess/metrics/gather.py, gmprocess/metrics/imc/arithmetic_mean.py, gmprocess/metrics/imc/channels.py, gmprocess/metrics/imc/geometric_mean.py, gmprocess/metrics/imc/gmrotd.py, gmprocess/metrics/imc/greater_of_two_horizontals.py, gmprocess/metrics/imc/quadratic_mean.py, gmprocess/metrics/imc/radial_transverse.py, gmprocess/metrics/imc/rotd.py, gmprocess/metrics/imt/arias.py, gmprocess/metrics/imt/fas.py, gmprocess/metrics/imt/pga.py, gmprocess/metrics/imt/pgv.py, gmprocess/metrics/imt/sa.py, gmprocess/metrics/station_summary.py, gmprocess/plot.py, gmprocess/report.py, tests/gmprocess/io/asdf/stream_workspace_test.py, tests/gmprocess/metrics/stationsummary_test.py
- added station metrics to StreamWorkspace
- now calculating stream/station metrics at the same time in gmprocess2
- created listmetrics script which dynamically lists valid IMC/IMT combinations
- changes in imc/imt classes to support listmetrics
- fixed issues in FDSN reader
=> A number of changes mostly supporting station metrics calculations.

gmprocess/stationtrace.py
I intended to do this in the last PR but forgot.
=> Change assert to exception in validate for better exception tracking

bin/gmprocess
* Eliminate positional arguments in `gmprocess` in favor of named arguments.
* Remove lazy logging.
* Remove unnecessary len(list).
In response to https://github.com/usgs/groundmotion-processing/issues/311
=> Use named arguments in gmprocess

gmprocess/io/fetch_utils.py, gmprocess/stationstream.py
- Fixed problem where trace slicing was getting applied every time a StationStream object was created, even if it wasn't necessar
- Modified the StationStream init to resample traces if slicing is unable to align the records
=> Snap traces from same instrument to same samples

gmprocess/io/fetch_utils.py
Color stations in station map by passed/failed status.
Improve land/water colors.
=> Color stations in station map by passed/failed status

gmprocess/io/fetch_utils.py, gmprocess/nn_quality_assurance.py, gmprocess/processing.py, gmprocess/stationstream.py, tests/gmprocess/stastream_test.py
- Adds a num_horizontal property to StationStream
- Same horiz corner frequencies will check if there are at at least two horizontals
- Fixes bug for lowest low pass frequency
=>  Num_horizontal property to StationStream

bin/gmprocess, docs/getting-started/running.md, docs/gmprocess/gmprocess.md, docs/gmprocess/waveform-processing.md, gmprocess/io/fetch_utils.py
- Minor tweaks to docs
- Fixed `get_events` so that it doesn't error out if it encounters a file name in the data directory that is something other than a directory named as an event id. This was causing execution to halt now that a log file is stored in this location.
=> Doc updates

docs/_sass/support/_variables.scss
Use blue for links and use same color for children links in navigation bar.
=> Fix navigation link color (use blue).

docs/_includes/nav.html
Only show subsection in navigation panel when parent of subsection or one of the subsections is selected.
=> Fix showing/hiding navigation detail

gmprocess/io/asdf/stream_workspace.py, gmprocess/io/fdsn/fdsn_fetcher.py
FDSN providers that are temporarily unavailable should no longer cause an error when initializing clients.
=> Depth in kilometers, and FDSN clients fix.

gmprocess/io/asdf/stream_workspace.py
=> Added workspace format version; changed workspace open method

bin/gmprocess, gmprocess/io/asdf/stream_workspace.py, gmprocess/report.py, tests/bin/gmprocess_test.py
Fix minor bugs that come up when running 'report' option in separate gmprocess call
=> Report issues

gmprocess/data/config.yml
Change dd -> decimal degrees in description for FDSN fetcher on default configuration file.
=> Improve description of parameter in default configuration

gmprocess/data/config.yml, gmprocess/plot.py, gmprocess/spectrum.py, tests/gmprocess/spectrum_test.py
=> Updates to spectral fitting

gmprocess/plot.py, gmprocess/report.py
- Ensure event id string is tex-compatible (underscores are not)
- Work around a bug that occurs when no stations are plotted on the moveout figure
=> Remove and moveout plot fixes

bin/gmprocess, gmprocess/io/asdf/stream_workspace.py, gmprocess/io/fetch_utils.py, gmprocess/plot.py, tests/gmprocess/plot_test.py
- Improves the scaling of traces in the moveout plot. Scaling is dynamically determined based on the range of distances and amplitude variations. Closes #442 
- Improves the bounds on the station plot. Also adds a legend. I attached two figures that show an example map without this improvement, and the improved map. Closes #414
- Checking for unprocessed label, which fixes a problem where a workspace contained no data.
- A fix for when stream metrics are not found in the workspace.
=> Map and plots

gmprocess/io/esm/core.py, gmprocess/io/smc/core.py
- Handling raw European data (esm fmt)
- Handling missing year in SMC fmt
=> Format fixes

gmprocess/io/asdf/stream_workspace.py, gmprocess/stationtrace.py, tests/gmprocess/io/asdf/stream_workspace_test.py
When using the 'channels' IMC, the vertical component table should now contain the correct filter frequencies. The columns are now labeled as 'ZLowpass' and 'ZHighpass'. Closes #518
=> Fixing bug related to vertical component table.

bin/gmsetup
=> Fixed import

azure-pipelines.yml, gmprocess/apps/gmrecords.py, gmprocess/io/fetch_utils.py, gmprocess/io/global_fetcher.py, gmprocess/subcommands/assemble.py, gmprocess/subcommands/download.py, gmprocess/subcommands/projects.py, tests/gmprocess/subcommands/assemble_test.py
- separate assemble into two different subcommands: download, assemble
- minor updates to how projects work.
- add python 3.9 to azure pipelines
=> Separate download out of assemble

README.rst, docs/contents/getting-started/index.rst
All documentation will live in readthedocs now.
=> Remove wiki

docs/contents/tutorials/cli.rst, gmprocess/subcommands/base.py, gmprocess/subcommands/projects.py, gmprocess/utils/plot.py, tests/gmprocess/bin/gmrecords_test.py, tests/gmprocess/subcommands/assemble_test.py, tests/gmprocess/subcommands/compute_station_metrics_test.py, tests/gmprocess/subcommands/compute_waveform_metrics_test.py, tests/gmprocess/subcommands/export_failures_test.py, tests/gmprocess/subcommands/export_metric_tables_test.py, tests/gmprocess/subcommands/export_provenance_tables_test.py, tests/gmprocess/subcommands/export_shakemap_test.py, tests/gmprocess/subcommands/generate_regression_plot_test.py, tests/gmprocess/subcommands/process_waveforms_test.py, tests/gmprocess/subcommands/projects_test.py
- Formatting fixes.
- Request name of local project; the default name is "default". 
- Don't halt execution if no processed waveforms are found. Closes #603.
- Added some validation of name/email.
=> Minor tweaks

gmprocess/subcommands/base.py, gmprocess/subcommands/compute_station_metrics.py, gmprocess/subcommands/compute_waveform_metrics.py, gmprocess/subcommands/export_failure_tables.py, gmprocess/subcommands/export_metric_tables.py, gmprocess/subcommands/export_provenance_tables.py, gmprocess/subcommands/export_shakemap.py, gmprocess/subcommands/generate_report.py
Gracefully deal with events that have no processed waveforms (Closes #611)
=> Handle lack of processed streams

gmprocess/subcommands/assemble.py, gmprocess/subcommands/compute_station_metrics.py, gmprocess/subcommands/compute_waveform_metrics.py, tests/gmprocess/subcommands/assemble_test.py, tests/gmprocess/subcommands/compute_station_metrics_test.py, tests/gmprocess/subcommands/compute_waveform_metrics_test.py, tests/gmprocess/subcommands/process_waveforms_test.py
=> Added dask to more subcommands

README.rst, docs/README.rst, tests/gmprocess/subcommands/export_failures_test.py
=> Add citation info to docs

gmprocess/subcommands/projects.py
=> Ensure absolute conf paths

gmprocess/waveform_processing/processing.py
Address #612 to provide a function to check the number of channels, as well as requiring two horizontal channels.
=> Check characteristics of the instrument

gmprocess/bin/gmprocess2.py, gmprocess/data/config_production.yml, gmprocess/data/config_test.yml, gmprocess/io/asdf/stream_workspace.py, gmprocess/io/fetch_utils.py, gmprocess/metrics/station_summary.py, gmprocess/subcommands/base.py, gmprocess/subcommands/export_shakemap.py, gmprocess/utils/constants.py, gmprocess/waveform_processing/processing.py, tests/gmprocess/subcommands/export_shakemap_test.py
- add deprecation warnings.
- add new json station data format
- updated default config to use check_instrument
- strip 'smi:local/' from event ids in exported tables (closes #620)
=> Added new json station format

gmprocess/io/report.py, gmprocess/subcommands/generate_report.py
=> Prepend project and label to report file name

gmprocess/io/cosmos/cesmd_fetcher.py, gmprocess/io/cosmos/cesmd_search.py
CESMD web service output groups metadata for stations for one event in multiple instances of event dictionary objects. Not sure why this is the case, but have adapted the code to match the format.
=> Hopefully fixed bug in cesmd fetcher

gmprocess/io/cosmos/core.py
=> Update COSMOS tables

gmprocess/io/read_directory.py
=> Handle read exception

gmprocess/io/cosmos/core.py, gmprocess/io/dmg/core.py, gmprocess/io/smc/core.py, tests/gmprocess/core/streamcollection_test.py, tests/gmprocess/io/dmg/dmg_test.py, tests/gmprocess/waveform_processing/windows_test.py
=> Change unknown network code to --

.coveragerc, .gitignore, gmprocess/data/config_production.yml, gmprocess/data/config_test.yml, gmprocess/io/asdf/stream_workspace.py, gmprocess/metrics/metrics_controller.py, gmprocess/metrics/reduction/arias.py, gmprocess/metrics/reduction/duration.py, gmprocess/metrics/reduction/max.py, gmprocess/metrics/reduction/null_reduction.py, gmprocess/metrics/reduction/percentile.py, gmprocess/metrics/reduction/reduction.py, gmprocess/metrics/reduction/smooth_select.py, gmprocess/metrics/reduction/sorted_duration.py, gmprocess/metrics/station_summary.py, gmprocess/utils/constants.py, tests/gmprocess/metrics/imt/duration_test.py
=> Duration updates

gmprocess/waveform_processing/snr.py
Fixes #653. Test the usable frequency range before applying the mask.
=> Fixed #653

gmprocess/utils/config.py
I believe that this closes #671 and #670. Please test and let me know if the problems persist.
=> Config bugfix

gmprocess/subcommands/base.py, gmprocess/subcommands/compute_station_metrics.py, gmprocess/subcommands/compute_waveform_metrics.py, gmprocess/subcommands/export_failure_tables.py, gmprocess/subcommands/export_metric_tables.py, gmprocess/subcommands/export_provenance_tables.py, gmprocess/subcommands/export_shakemap.py, gmprocess/subcommands/process_waveforms.py
=> Handle events with no data without erroring

gmprocess/io/cosmos/cesmd_fetcher.py, gmprocess/io/fetch_utils.py, gmprocess/io/fetcher.py, gmprocess/io/geonet/geonet_fetcher.py, gmprocess/io/global_fetcher.py, gmprocess/io/knet/knet_fetcher.py, gmprocess/io/obspy/fdsn_fetcher.py, gmprocess/subcommands/download.py
=> Turn off streamcollection construction for download

gmprocess/utils/usgs_id_cross_reference.py
Algorithm for cross-referencing outside project earthquake IDs to USGS IDs.
=> usgs id cross reference

gmprocess/subcommands/compute_station_metrics.py, gmprocess/subcommands/compute_waveform_metrics.py, gmprocess/subcommands/export_failure_tables.py, gmprocess/subcommands/export_metric_tables.py, gmprocess/subcommands/export_provenance_tables.py, gmprocess/subcommands/generate_report.py
=> Deal with pstreams being empty AND nonexistent

gmprocess/waveform_processing/processing.py
=> Fix time array in baseline correction

README.rst, gmprocess/data/config_production.yml, gmprocess/waveform_processing/clipping/clip_detection.py, gmprocess/waveform_processing/clipping/clipping_check.py, gmprocess/waveform_processing/processing.py, gmprocess/waveform_processing/snr.py, tests/gmprocess/waveform_processing/clipping/clipping_check_test.py, tests/gmprocess/waveform_processing/clipping/ping_test.py
- Added clipping to processing steps
- Include broadband stations by default now
- Remove codacy from readme
=> Add clipping test to processing steps

gmprocess/core/streamcollection.py, gmprocess/io/report.py
=> Sort stations in report

gmprocess/io/fetch_utils.py
Deafault to downloading the geojson file from comcat and extracting the relevant information for the event object.
The event reader is backwards compatible with the old format.
This should resolve Issue #717
=> Use comcat geojson files

gmprocess/apps/gmrecords.py, gmprocess/subcommands/projects.py, gmprocess/utils/config.py
Now that I've done this, it feels like absolute paths are just a lot easier to work with. 
Closes #709.
=> Switch to relative paths in projects conf

gmprocess/utils/plot.py
=> Add peak values to report plots

gmprocess/io/cosmos/cesmd_search.py, gmprocess/io/geonet/geonet_fetcher.py, gmprocess/io/knet/knet_fetcher.py, gmprocess/io/nsmn/turkey_fetcher.py, gmprocess/io/obspy/fdsn_fetcher.py
Will close https://github.com/usgs/groundmotion-processing/issues/708
Getting the logging file name from the handler was a little tricky so the reviewer may want to check this way is not terrible:
for handler in root.handlers:
if hasattr(handler, "baseFilename"):
log_file = getattr(handler, 'baseFilename')
Autopep8 ran & pytest pass
=> Debug log url

gmprocess/io/asdf/stream_workspace.py, gmprocess/io/fetch_utils.py, gmprocess/io/obspy/fdsn_fetcher.py
This should close https://github.com/usgs/groundmotion-processing/issues/468
Also includes a bug fix for the debug url logger for obspy's massdownloader.
=> Read config asdf

gmprocess/apps/gmrecords.py, gmprocess/core/stationtrace.py, gmprocess/io/asdf/core.py, gmprocess/io/asdf/stream_workspace.py, gmprocess/io/report.py, gmprocess/subcommands/assemble.py, gmprocess/subcommands/generate_report.py, gmprocess/subcommands/process_waveforms.py, gmprocess/utils/assemble_utils.py, gmprocess/utils/export_shakemap_utils.py
Closes #781. Couldn't get away with only one call.
=> Minimize calls to get_version

gmprocess/io/read.py, gmprocess/subcommands/assemble.py, gmprocess/subcommands/clean.py, gmprocess/subcommands/compute_station_metrics.py, gmprocess/subcommands/compute_waveform_metrics.py, gmprocess/subcommands/download.py, gmprocess/subcommands/export_failure_tables.py, gmprocess/subcommands/export_metric_tables.py, gmprocess/subcommands/export_provenance_tables.py, gmprocess/subcommands/export_shakemap.py, gmprocess/subcommands/generate_regression_plot.py
Closes #784. I also wrapped a bunch of paths with `os.path.normpath` to make prints to terminal less ugly now that we are using relative paths internally.
=> Guess format from extension

gmprocess/core/streamcollection.py, gmprocess/utils/config.py, gmprocess/waveform_processing/processing.py
=> Allow for magnitude-distance-based channel preference order

gmprocess/core/streamcollection.py
=> Ignore failed streams when checking colocated instruments

gmprocess/io/asdf/stream_workspace.py, gmprocess/subcommands/export_metric_tables.py
=> Handle empty metrics more gracefully

gmprocess/data/config_production.yml, gmprocess/data/config_test.yml, gmprocess/subcommands/base.py, gmprocess/subcommands/generate_report.py, gmprocess/waveform_processing/corner_frequencies.py, gmprocess/waveform_processing/processing.py, tests/gmprocess/subcommands/process_waveforms_test.py, tests/gmprocess/waveform_processing/corner_frequencies_test.py, tests/gmprocess/waveform_processing/spectrum_test.py, tests/gmprocess/waveform_processing/windows_test.py
=> Add support for magnitude-based filter corners

gmprocess/apps/gmrecords.py
Changes to GMrecordsApp:
* Add `kwargs` argument to `main()` which can be used in place of command line arguments.
* Don't parse command line arguments in constructor (do at beginning of `main()`).
* Add `_initialize()` method for loading config and initializing logging.
* Add `load_subcommands()` method for loading subcommands information. This makes it easy for scripts to set `func` for the desired subcommand.
Closes #885
=> Refactor GMrecordsApp() constructor and main to allow scripting.

gmprocess/io/obspy/fdsn_fetcher.py
Handles new ObsPy logging configuration for the MassDownloader object and still allows for use of older ObsPy releases using the previous logging setup.
Resolves #894
=> Update FDSN logging configuration

gmprocess/core/stationstream.py, gmprocess/io/asdf/stream_workspace.py, gmprocess/subcommands/process_waveforms.py
Fixes but in previous update to parse manually reviewed data; this bug had been occurring for stations with multiple instruments.
=> Fix overwrite of reprocessed waveforms

gmprocess/io/cosmos/cosmos_writer.py
Some minor formatting tweaks, allow for multiple streams at the same station, avoid error when no traces are processed. Partially address #913.
=> COSMOS writer tweaks

gmprocess/io/global_fetcher.py
Thanks for @smithj382 for pointing this out and giving the solution.
=> Fetcher bugfix

src/gmprocess/subcommands/assemble.py, src/gmprocess/subcommands/compute_waveform_metrics.py, src/gmprocess/subcommands/generate_report.py, src/gmprocess/subcommands/process_waveforms.py, src/gmprocess/utils/assemble_utils.py
=> Replace ThreadPoolExecutor with ProcessPoolExecutor

src/gmprocess/utils/report_utils.py
=> FIX: Fix swapped labels in station map legend. Add network code to station tooltip.

src/gmprocess/subcommands/assemble.py, src/gmprocess/subcommands/compute_waveform_metrics.py, src/gmprocess/subcommands/generate_report.py, src/gmprocess/subcommands/process_waveforms.py
=> Fix but in call to ProcessPoolExecutor

src/gmprocess/subcommands/process_waveforms.py
=> Fix location of logging statement

src/gmprocess/apps/gmrecords.py, src/gmprocess/subcommands/projects.py
I think this undoes a mistake I made in #1022.
=> Always print absolute project paths

setup.py
=> FIX: Re-add setup.py so editable installs work with older versions of pip

doc_source/contents/developer/changelog.md, src/gmprocess/waveform_processing/corner_frequencies.py, tests/gmprocess/io/obspy/obspy_test.py
=> Add maximum lp corner option

src/gmprocess/subcommands/compute_station_metrics.py
=> Rupturefix
