usgs/groundmotion-processing

- bin/gmsetup
- gmprocess/corner_frequencies.py
- gmprocess/data/config.yml
- gmprocess/logging.py
- gmprocess/plot.py
- gmprocess/pretesting.py
- gmprocess/processing.py
- gmprocess/windows.py
- tests/gmprocess/processing_test.py
Closes #65. Also:
- Checks so that it doesn't apply sensitivity correction if data units are not in counts
- Resolve some lookup of processing params inconsistencies
- Changes default filtering method to use constant corners; this is primarily so that tests don't have to change while we refine the corner frequency picking algorithm. 
- Changed the setup_logger method so that it can be called without command line args. Useful when debugging the code as a library. 
- Re-organized how the pretesting methods work.
> Fix corner freq bug and misc cleanup

- .gitignore
- docs/workspace.md
I think Eric's original order of IM -> IMT makes more sense, because
1. The different metric types (maximum, geometric mean, RotD50) are all grouped together.
2. Users are more interested in the metric than the metric type so it 
should be at a higher level, and 
3. We often compute multiple metric types at a time (for example, RotD50 and RotD100).
> Switched waveform metrics grouping to IM -> IMT.

- gmprocess/corner_frequencies.py
- gmprocess/data/config.yml
- gmprocess/processing.py
- Adds a resampling method using Lanczos interpolation.
- Fixes bug in corner frequencies where the low corners and high corners were swapped if the SNR was greater than the threshold at the first frequency.
Closes #9
> Resampling and corner frequency bug fix

- bin/fdsnfetch
- gmprocess/data/config.yml
- gmprocess/io/dmg/core.py
- gmprocess/io/usc/core.py
- gmprocess/io/utils.py
- tests/gmprocess/io/usc/usc_test.py
- Handles unevenly-spaced times in USC and DMG files by checking for a constant time delta, then uses linear interpolation to resample the data. A default resampling rate of 200 Hz is specified in the config.
- Fixes a bug in `fdsnfetch` where the origin arguments were not being passed correctly.
- Commented out several USC tests that were using unevenly-spaced data and now function incorrectly.
Closes #43
> Unevenly-spaced data

- gmprocess/data/CESMD_NGA_ids.csv
Add file for correspondance between cesmd event directory names and NGA event ids. This will help for any efforts to compare our processing of the CESMD data to what is in the NGA Flatfile.
> cesmd event dirs

- .travis.yml
The command in the .travis.yml was creating an error. I was looking at this to try to figure out why our codecov report is not getting updated.
> Remove codacy coverage stuff that we are not using

- README.rst
The issue seems to be something with access to the upstream repository. But it appears that as an admin of the repository, I do not have authority to install codecov integration so I think the only solution is to use my fork for tracking coverage. I think this should be okay as long as I keep my fork up to date but it is obviously not ideal.
> Changing coverage links in readme

- gmprocess/corner_frequencies.py
- gmprocess/metrics/imt/arias.py
- gmprocess/metrics/imt/fas.py
- gmprocess/metrics/imt/pga.py
- gmprocess/metrics/imt/pgv.py
- gmprocess/metrics/imt/sa.py
- gmprocess/metrics/station_summary.py
- gmprocess/processing.py
- tests/gmprocess/metrics/radial_transverse_test.py
- Reworked radial-transverse IMC to be consistent with other IMCS in the dictionary that it returns. This required modifying IMT files as well.
- `stationTrace.getParameter()` can either return a dict or list, so this required modifying some processing steps to check for a list vs. dict.
- Fixed an issue related to enforcing the same filter frequencies for horizontal channels
- Fixed an issue calculating frequencies associated with FAS periods.
- `stationStream.check_stream()` is now called before each processing step.
- `remove_response()` now directly converts data from m/s/s to cm/s/s.
- Fixed an issue in low pass filter such that the low pass filter is only applied if the filter frequency is less than the Nyquist frequency.
> Reworked radial-transverse IMC, various processing and metrics fixes

- gmprocess/corner_frequencies.py
- gmprocess/data/config.yml
- gmprocess/plot.py
- gmprocess/processing.py
- gmprocess/windows.py
- Window duration check was only checking for zero length vectors and was not controllable by the conf file; this makes it configurable and a distinct step in the processing workflow. When it was failing it was causing some weirdness because it would have to then pass by a bunch of code. 
- Renamed "plot_SNR" to "summary_plot" since it shows so much more than just SNR and in fact I think we should make the plot even if we can't get the SNR due to a lack of noise window.
> Moved window check to its own step

- gmprocess/corner_frequencies.py
- gmprocess/data/config.yml
- gmprocess/fft.py
- gmprocess/plot.py
- gmprocess/pretesting.py
- gmprocess/processing.py
- gmprocess/snr.py
- gmprocess/spectrum.py
- gmprocess/stationstream.py
- gmprocess/stationtrace.py
- gmprocess/windows.py
- tests/gmprocess/corner_frequencies_test.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
- tests/gmprocess/processing_test.py
- tests/gmprocess/spectrum_test.py
Note: the new plotting method has only undergone limited testing and there are probably some problems that will come up as it gets used with a wider range of data.
This PR includes lots of stuff, including:
- moved sta/lta checks to occur earlier in the default processing steps
- generally made things more modular (e.g., now we have 'fft.py' and 'snr.py' modules)
- changed scaling of fft
- corner frequency selection step is now not handled "specially"; it is just treated generically like most other processing steps
- adjusted processing.py to allow for steps with empty options
- made adjustments so summary plots can be made for all traces, regardless of check passes/failures, and refactored so that it makes more use of trace parameters for information rather than function arguments
- …
> Processing

- gmprocess/data/config.yml
- gmprocess/plot.py
- gmprocess/processing.py
- gmprocess/stationstream.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
- added a max_traces processing step to screen out StationStreams that have more than 3 stations.
- modified StationStream.get_id to not make use of location code; uses first two characters of the channel code instead.
- modify summary_plot to indicate if a trace has failed any tests
Decided to wait on adding the stream check failure reason text until we have a better solution for putting tabular information into the page, perhaps via embedding the figure into a latex document. 
We might want to reconsider not doing some of the processing steps even when the stream has been rejected.
> Plot tweaks

- gmprocess/pretesting.py
- gmprocess/processing.py
- gmprocess/snr.py
- gmprocess/spectrum.py
- gmprocess/stationstream.py
- tests/gmprocess/corner_frequencies_test.py
Move `stream.passed` check inside processing step methods, rather than outer `process_streams`. This is to allow some steps to occur regardless of whether or not the stream has passed checks (such as computing the signal spectrum, which would be nice to have in the summary plots even if a check has failed). I also expect that some steps might eventually have the ability to "un-fail" a stream. For example, if the noise windowing fails, but we are able to pick reasonable corner frequencies solely on the signal spectra. This will require a failure status system that is a bit more complicated than what we are currently doing because other checks should not be allowed to be "undone" by downstream steps, such as the free field check.
> Reorganize status checks

- gmprocess/processing.py
Instrument response removal was only performed for strong motion instruments when the data was in integers. However, uncorrected data will not always be in integers (such as if the data has been demeaned). Instrument response correction will now check if a provenance entry ('remove_response') has already been set before removing response.
> Instrument response correction fix for strong motion instruments.

- gmprocess/pretesting.py
Amplitude check now checks for 'remove_response' provenance entry instead of checking for integer-valued data.
> Bug fix for maximum amplitude check.

- gmprocess/processing.py
A variety of errors can occur when deconvolving instrument response, likely due to incorrect response metadata. Traces that encounter errors or result in non-finite values after response removal will now fail.
> Additional checks for remove response

- gmprocess/event.py
- tests/gmprocess/event_test.py
The event.get_event_object() in creating an Origin object from a dict
needs to transfer the origin time from the dict to the Origin object.
event_test.py needs to be updated to be more rigorous.
> event.get_event_object() needs to set time attribute.

- bin/datafetch
I discovered today, when processing waveforms for us700038c1, that if you request the amptools file but leave the output format for metrics to be default (csv) then the amptools file doesn't get created. This PR fixes that issue since these are two separate files and the format of the station summary file should not affect the amptools file.
> Disentangle metric format from amptools file

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/processing.py
- gmprocess/stationstream.py
- gmprocess/streamcollection.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
- Added provenance logging when StationStream trims record (this is in the init and thus is not part of the processing steps where logging is more reliably handled).
- Detect if the trim is going to cause an error in ObsPy so that we can fail the trace rather than raise an exception that halts processing from proceeding.
- Fixed bug in StationStream where it can't find a tag for an empty StationStream. 
- Improved handling of tag in StreamCollection grouping method. 
- Changed StationStream validate to label the stream as failed rather than raise an exception. 
- Added some additional validation to StationStream.
- Check that label does not have an underscore in it since we use that character to split to separate out the station and the label from the tag.
- Removed "test_raw" because we …
> Misc updates

- gmprocess/plot.py
- gmprocess/windows.py
- Changed tr.stats.times('utcdatetime')[0] to tr.stats.starttime in signal split.
- Instead of using plt.tight_layout(), it's faster to use plt.subplots_adjust() in the summary plots.
> Optimizations to plotting and signal split.

- gmprocess/zero_crossings.py
- Modify zero crossings to include last datapoint (does not have practical importance but it is cleaner)
- Add trim step prior to zero crossing calculation (though it doesn't actually preserve the trim)
Closes #265
> Zero crossing update

- README.rst
To prevent people from using the conda channel right now.
> conda warning

- docs/_config.yml
Use `remote_theme` instead of `theme` in `_config.yml` when using an open source Jekyll theme instead of an official GitHub pages theme.
> Fix theme specification (remote_theme for open-source theme).

- gmprocess/streamcollection.py
It is possible that automated queries could result handing off an empty list of streams to streamcollection and it just needed a slight tweak so that it doesn't error out in this case.
> Handle case where no traces are handed to streamcollection

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/stationstream.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
- Change `workspace.getLabels` to get labels from waveforms rather than provenance. The error @jrekoske-usgs  was getting was because raw data does not have a provenance document and so the unprocessed record labels were not getting discovered
- Fixed duplicate eventid in provenance document path
- Fixed some tests to use pytest.raises to check for whether or not functions appropriately raise exceptions
Closes #283
Closes #296
> Fix issues with tags and labels

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/io/dmg/core.py
- gmprocess/io/fdsn/core.py
- gmprocess/stationstream.py
- IMTs now sorted correctly in metrics tables. Closes #338 
- Adjusted dmg reader to be able to read some additional time formats. Elevation set to 0.0 instead of np.nan which causes problems.
- FDSN reader location and channel naming is now consistent with other readers
- Fixed StationStream problem that was trying to check the time windows of constituent traces (the problem was that '&' has higher operator precedence over '==', needed to change to 'and'). Also now checks that azimuth is in the range [0,360] to prevent obspy from raising exceptions.
>  Sorting IMTs, dmg/fdsn updates, and fixing stream workspace exceptions.

- tests/gmprocess/streamcollection_test.py
Fix test of how duplicates are handled. The test behavior presumably changed when @jrekoske-usgs fixed the DMG reader to correctly read in the time in a recent pull request. It is not clear why the tests didn't fail previously.
> Fix duplicates test

- docs/_data/navbar.yml
- docs/processing-steps/waveform-processing/filtering.md
- docs/processing-steps/waveform-processing/initial-qc.md
- gmprocess/processing.py
- tests/gmprocess/corner_frequencies_test.py
- At some point we broke the `same_horiz` option for `get_corner_frequencies` and we didn't have good enough tests to realize
- This un-breaks that option and improves the tests
- Some small updates to docs on filtering; trying to explain the filtering algorithm is how I discovered the problem with the `same_horiz` option
> Filtering updates

- bin/gmprocess
- gmprocess/io/fdsn/core.py
- gmprocess/nn_quality_assurance.py
- tests/gmprocess/corner_frequencies_test.py
- gmprocess can now handle being passed a directory that contains a subdirectory for each event
- Adjusted FDSN reader to only accept StationXML files with name formatted as NET.STA.xml. This is a just temporary fix to proceed with processing, as the wildcard matching was causing problems for stations such as AV.ILW and AV.ILSW. This method works with all the files we create internally, the only problems could come up if someone tries to read StationXML files they created elsewhere. See #292. 
- Some additional checks before running the nnet.
> Multiple event directory, fdsn reader, and nnet checks

- gmprocess/processing.py
Makes sure that streams pass before enforcing the same corner frequencies across the horizontals. This makes sure that if corner_frequencies.snr fails, then we won't get an error trying to access the corner frequencies.
> Fixing problem in corner frequencies.

- docs/_sass/layout.scss
- docs/_sass/typography.scss
* Increase banner size and padding around USGS logo.
* Improve style of headings (all bold except h1; gradually decrease font size).
> Fix banner padding and format of headings in documentation

- docs/_data/navbar.yml
Fix navbar yaml file for addition of gmconvert section (missing subitems heading).
Fix some typo.
Fix link to converting.md.
> Fix addition of gmconvert section in navigation bar in docs

- docs/_sass/code.scss
- docs/_sass/custom/custom.scss
- docs/_sass/support/_variables.scss
Reduce the size of the box around inline code blocks and adjusted the line spacing to eliminate overlap between boxes and adjacent lines. 
Use a slightly darker background for code so it is more visible.
> Fix line spacing (eliminate overlap with code bg) and darken bg for code.

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/metrics/station_summary.py
Hypocentral distance calculations should be fixed. The lat sand lons needed to be switched in the function call to openquake.hazardlib.geo.geodetic.distance().
> Fixing hypocentral distance calculation bug

- bin/gmprocess
- gmprocess/io/asdf/core.py
- gmprocess/io/asdf/stream_workspace.py
- gmprocess/snr.py
- gmprocess/streamcollection.py
- tests/gmprocess/corner_frequencies_test.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
- tests/gmprocess/nn_quality_assurance_test.py
- Reinstates the workspace close method to ensure that HDF5 files are properly flushed
- Noise and signal windows are each demeaned individually before computing SNR
- Fix for checking duplicates that have different channel names (e.g. HN1 vs HNN)
- Some tests needed updating because of the different SNR calculation, resulting in different corner frequencies
> Workspace close, noise/signal detrending, and duplicate checking

- gmprocess/data/config.yml
Lowered the default value for the Nyquist-based cap on the lowpass corner frequency in the config file.
> Revise lowpass cap

- bin/gmprocess
- gmprocess/event.py
- gmprocess/io/fetch_utils.py
- `get_event_dict` will now raise a warning if the ID of the returned event object is different than the input event ID.
- If the --directory argument is used in `gmprocess`, then the event folders in the directory will be renamed if the preferred event ID is different from the folder name. A warning is also issued when this happens. This is to prevent an error constructing paths when the preferred event ID might have been changed in ComCat. We also now ignore hidden files to prevent annoying warnings for folders like .DS_Store on Mac. Closes #421. 
- Fix for handling magnitude type when the --eventinfo argument is used
> Handling updated event ids and magnitude type stuff.

- bin/gmprocess
- gmprocess/io/asdf/stream_workspace.py
- gmprocess/plot.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
- For each exported IMC table, we now also create a README table which describes all of the columns from the IMC table. The README tables are created using `workspace.getTables()`. Closes #445 
- Improving the help string for the `--status` argument to be more descriptive.
> README tables

- bin/gmprocess
- gmprocess/io/asdf/stream_workspace.py
- gmprocess/spectrum.py
- Adds a method to stream_workspace for retreiving a DataFrame of the fit_spectra parameters for all streams in the workspace. Also returns a README DataFrame.
- Using `gmprocess --export` will call this new method and save the fit_spectra parameters and README to the output directory.
> Stress drop parameters

- gmprocess/metrics/combination/combination.py
- gmprocess/metrics/metrics_controller.py
- gmprocess/metrics/reduction/arias.py
- gmprocess/metrics/rotation/rotation.py
- gmprocess/metrics/transform/differentiate.py
- gmprocess/metrics/transform/fft.py
- gmprocess/metrics/transform/integrate.py
- gmprocess/metrics/transform/transform.py
FFT transform for FAS calculations now checks if the spectra have already been computed, which speeds things up when looping over lots of periods. Closes #412 
This also speeds up metrics calculations by avoiding making copies of streams (which is expensive). Instead of always making copies, we only make copies now when the data is directly modified (such as integrate and differentiate methods).
> Metrics speedup and optimization.

- gmprocess/data/testdata/config_min_freq_0p2.yml
- gmprocess/processing.py
- gmprocess/snr.py
- tests/gmprocess/corner_frequencies_test.py
- tests/gmprocess/io/asdf/asdf_layout_test.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
- tests/gmprocess/processing_test.py
- Adds a new config option that allows the minimum frequency for SNR check to be a function of magnitude. This is now the new default. The minimum frequency scales with magnitude according to the attached figure. The ceiling and stress drop can be configured (defaults are 2.0 Hz and 10 bars).
- Removed a duplicate, unused function from `processing.py`
- Updated some tests that were dependent on the minimum frequency being set at 0.2 Hz to use a  dedicated config file.
> Minimum frequency function of magnitude.

- gmprocess/data/config.yml
- gmprocess/snr.py
Sets a minimum frequency floor option. Default is 0.1 Hz.
> Minimum frequency floor

- gmprocess/io/fetch_utils.py
Fixes an issue with the mapping code identified by Diego from University of Puerto Rico. For cases where the station locations are very close to the event location, the error AttributeError: 'list' object has no attribute 'xy'  was being generated. This fixes this by requiring a minimum value of the width and height for the map.
> Map fix for stations close to event epicenter.

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/spectrum.py
- Fixes an error in the Raoof 99 geometrical spreading attenuation equation.
- Adds two metrics for measuring the goodness-of-fit for the Brune spectral fitting: mean squared error and R^2. These will be saved in the fit_spectra_parameters.csv and README files.
> Fixing Raoof 99 attenuation function and adding spectral misfit metrics.

- gmprocess/stationtrace.py
`StationTrace.stats.standard.source` will now contain both the `Source` and `Sender` from the `StationXML` unless they are the same.
> Use both source & sender unless theyre the same

- azure-pipelines.yml
Python version was not specified in azure pipelines previous for windows builds.
> Set python version for windows in azure builds

- gmprocess/io/cosmos/cesmd_search.py
The `encoding` keyword shouldn't be specified on binary files. This was causing an exception Python 3.7.
> Fixed: encoding on binary output.

- gmprocess/core/streamcollection.py
- gmprocess/subcommands/export_failure_tables.py
- tests/gmprocess/core/streamcollection_test.py
Fixed headers not appearing on some failure tables. The headers are now added in `streamcollection.get_status()`. Also adjusted some column names to be consistent with other outputs (e.g. 'EarthquakeId' instead of 'Event ID').
> Failures tables headers.

- gmprocess/metrics/metrics_controller.py
- gmprocess/metrics/reduction/max.py
- gmprocess/metrics/transform/integrate.py
- tests/gmprocess/metrics/peak_time_test.py
For any calculation of PGA, PGV, and PGD, the time corresponding to the peak value will be stored within the stats section of the traces. For example, if StationSummary.from_stream is used to get the IMTS, PGA and PGV, and the IMC, CHANNELS, then following the processing the stats "pga_time" and "pgv_time" will be in each trace within the stream. The time is obspy's UTCDatetime format.
> Update the metric controller to store peak value time

- gmprocess/io/cosmos/cesmd_fetcher.py
- gmprocess/io/fetch_utils.py
- gmprocess/io/nga.py
- gmprocess/io/obspy/fdsn_fetcher.py
It is useful to re-run the download command and accumulate FDSN results because there are can be server/connection issues that cause data to be missed.
> Remove deletion of previously downloaded FDSN files

- gmprocess/io/fetch_utils.py
- gmprocess/metrics/reduction/max.py
This makes `compute_waveform_metrics` more than 5 times faster in my testing! :satisfied:
> Faster computation of trace times

- gmprocess/io/asdf/stream_workspace.py
This was the intended original behavior, but it looks like it was just a small typo that caused these columns to be included.
> Remove empty IMT columns

- gmprocess/utils/plot.py
Adds a plotting function for producing a figure that shows the oscillator response time series and max values for a given StationStream. An example is shown below.
> Oscillator Plot

- gmprocess/io/global_fetcher.py
- gmprocess/io/report.py
Fixed testing of stream length. I was getting errors in some cases where streams got set to `None`. This test should work for both cases (zero length and `None` values).
The report used Helvetica font, which requires a pretty big (1 GB) font file on Ubuntu. I changed the font to be a standard sans serif font. The previous document class used 9pt, which isn't supported by the article class, but is supported by the extarticle class.
> Two minor changes

- gmprocess/subcommands/process_waveforms.py
- gmprocess/utils/constants.py
This fixes the problem that many people have been having that is due to the default being a timestamp. The problem is that most people expect that when they re-run processing without specifying a label that they results will be overwritten. By making the default label a timestamp, this preserves all processing attempts unless the user specifies the labels.
> Change default label to `default`

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/subcommands/base.py
- gmprocess/subcommands/compute_station_metrics.py
- gmprocess/subcommands/compute_waveform_metrics.py
- gmprocess/subcommands/process_waveforms.py
- tests/gmprocess/io/asdf/stream_workspace_test.py
As a first step towards #710, `adjust compute_station_metrics`, `compute_waveform_metrics`, and `process_waveforms` subcommands to not pre-load all the streams for a given event. Instead, these now load one stream at a time within the loop. This should help with future optimization efforts, and maybe even will be somewhat more efficient from not having to load so much into memory all at once.
> Do not create list of all streams prior to loops

- gmprocess/data/config_production.yml
Short term measure to avoid problematic networks reported in #780.
> Exclude networks giving spurious results

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/subcommands/compute_station_metrics.py
- gmprocess/subcommands/compute_waveform_metrics.py
- gmprocess/subcommands/export_metric_tables.py
- gmprocess/subcommands/generate_report.py
- gmprocess/subcommands/generate_station_maps.py
- gmprocess/subcommands/process_waveforms.py
Closes #779. The source of the problem is that we have some IMT-IMC combos that don't make sense (e.g., ROTD50 and FAS). These give all nans in the columns for FAS in the ROTD50 table, which is inconvenient and looks bad. So we tried removed any columns in which all rows were nans. But this creates a mismatch from event-to-event if there are sometimes columns that are all nans for other reasons, and we didn't anticipate this. The updated code now removes all the FAS columns if the contents are all nans. This resolves the problem in the data provided by @arkottke and I believe that it solves the problem more generally.
> Fix mis-aligned columns in metric tables

- gmprocess/data/config_production.yml
- gmprocess/data/config_test.yml
- gmprocess/data/testdata/conf_small.yml
- gmprocess/data/testdata/config_min_freq_0p2.yml
- gmprocess/waveform_processing/processing.py
- tests/gmprocess/waveform_processing/lowpass_max_test.py
This changes the output on the `remove_response` function from acceleration to velocity, and then differentiates the result, as suggested [here](https://github.com/usgs/groundmotion-processing/issues/772#issuecomment-967207056). Also, I removed `output` as an option from the config, and this will break for anyone who is using an older config with the updated code.
> Adjust response removal for ?H? instruments

- gmprocess/io/asdf/stream_workspace.py
- gmprocess/subcommands/compute_station_metrics.py
- gmprocess/subcommands/export_metric_tables.py
- gmprocess/subcommands/generate_report.py
- gmprocess/subcommands/generate_station_maps.py
Avoid exceptions when running subcommands with no waveform data.
Allows the following subcommands to fail gracefully (print warning without throwing exception):
* compute_station_metrics
* export_metric_tables
* generate_report
* generate_station_maps
> Fail gracefully (avoid raising exceptions) in subcommands when there is no waveform data

- gmprocess/core/streamcollection.py
Add debug logging message when omitting station traces from stream collection because they are not free field.
> Add debug message when omitting station traces from stream collection

- gmprocess/waveform_processing/adjust_highpass.py
When adjust_highpass method is uncommented in the config file, the integration method used is not updated to the new scheme. This updates the integration method to match the previous changes.
> Fix integration method in adjust_highpass method.

- gmprocess/apps/gmrecords.py
Replace hardwired `log.txt` filename for log in GMrecordsApp with user-specified filename via `--log=FILE`.
**Note**: Requires merging PR #888 first.
Closes #887
> GMrecordsApp: Use user-specified filename for log

- gmprocess/apps/gmrecords.py
- gmprocess/core/streamarray.py
- gmprocess/core/streamcollection.py
- gmprocess/subcommands/assemble.py
- gmprocess/subcommands/base.py
- gmprocess/utils/assemble_utils.py
- gmprocess/utils/logging.py
* Turn off logging to stream (stdout) if using log file.
* Replace `print()` with `logging.info()` except for error messages and interaction with user.
* Fix StreamArray and StreamCollection `describe()`
* Return str instead of print to stdout.
* Log stream array info regardless of size (formerly only logged if nonzero size).
* Change logging level for display from `debug` to `info`.
**Note**: Should be merged after #889.
Closes #886
> Proposed fix for cleaning up logging

- gmprocess/core/streamarray.py
- gmprocess/core/streamcollection.py
- gmprocess/utils/assemble_utils.py
- gmprocess/utils/download_utils.py
Changes the existing `describe()` function, which returns a string literal, to a new function called `describe_string()` for both `StreamCollection` and `StreamArray`.
Another function which now takes the name `describe()` wraps the above and prints to sdtout, allowing for users to see formatted strings
> wrapper for describe() printing to stdout

- gmprocess/waveform_processing/adjust_highpass_ridder.py
- gmprocess/waveform_processing/filtering.py
Updated adjust_highpass_ridder.py to pass the highpass frequency_domain config option to Scott's cython code, so that the high pass corner is chosen using the same filter implementation that will subsequently be applied to the record.
> Ridder filter options

- gmprocess/io/read_directory.py
This is a very kludgy fix of #899 , where `shutil.rmtree` fails to fully remove temporary directories created in `read_directory.py` due to the presence of `.DS_Store` file that is generated if a user looks at the `data/raw/` directory in the Mac OS Finder. 
For reasons that remain inexplicable and will likely join other mysteries such as "What's the meaning of Stonehenge?", despite failing, if `shutil.rmtree` is just re-run on the temp directory, it removes it without error.
If anyone experiences this issue or has some insight into its origin, perhaps we can come up with a more elegant solution.
> Handle failed temp directory deletion

- gmprocess/apps/gmrecords.py
- gmprocess/core/stationtrace.py
- gmprocess/io/asdf/stream_workspace.py
- gmprocess/subcommands/process_waveforms.py
- gmprocess/waveform_processing/processing.py
- gmprocess/waveform_processing/zero_crossings.py
Closes #896. @meramossepu, please let me know if you run into any issues with this. This pull request adds the `-r` flag for "reprocess" to the `process` subcommand:
```
$ gmrecords process -h
usage: gmrecords process_waveforms [-h] [-e EVENTID [EVENTID ...]] [-t TEXTFILE] [-l LABEL] [-r] [-n n]
optional arguments:
-h, --help            show this help message and exit
-e EVENTID [EVENTID ...], --eventid EVENTID [EVENTID ...]
Comcat event ID. If None (default) all events in project data directory will be used.
-t TEXTFILE, --textfile TEXTFILE
Text file containing lines of ComCat Event IDs or event information (ID TIME LAT LON DEPTH MAG).
-l LABEL, --label LABEL
Processing label (single word, no spaces) to attach to processed files. Default label is 'default'.
-r, --reprocess …
```
> Handle UCLA manual review data in ASDF file

- gmprocess/core/stationtrace.py
- gmprocess/data/config_production.yml
- gmprocess/data/config_test.yml
- gmprocess/metrics/rotation/null_rotation.py
- gmprocess/metrics/rotation/radial_transverse.py
- gmprocess/metrics/rotation/rotation.py
- gmprocess/metrics/rotation/rotd.py
- gmprocess/metrics/transform/differentiate.py
- gmprocess/metrics/transform/fft.py
- gmprocess/metrics/transform/integrate.py
- gmprocess/metrics/transform/null_transform.py
- gmprocess/metrics/transform/oscillator.py
- gmprocess/metrics/transform/transform.py
- gmprocess/waveform_processing/clipping/jerk.py
- gmprocess/waveform_processing/processing.py
Allows you to configure whether or not you want frequency or time domian differentiation. Closes #938. Requires the following new section in the conf file:
```yaml
differentiation:
frequency: True
```
> Add freq differentiation option

- gmprocess/io/obspy/fdsn_fetcher.py
- gmprocess/subcommands/arg_dicts.py
- gmprocess/subcommands/download.py
- gmprocess/utils/base_utils.py
- gmprocess/utils/download_utils.py
- requirements.txt
- tests/gmprocess/io/obspy/fdsn_fetcher_test.py
- I tried to improve the help description for `textfile` (closes #929)
- pytest-recording (https://github.com/kiwicom/pytest-recording) is a wrapper around vcrpy to help with tests. I tried this and I couldn't get it to work with obspy so we're still not testing downloads.
- there was another bug in redirecting the obspy logger to the log file that I fixed. 
- The solution to the multiple event problem is to copy the conf within the event loop when handing it off to the download function (closes #944); I still have a hard time recognizing when python just creates a pointer rather than copy.
- This also improves support for events that are not in comcat.
> Fix multiple event bug

- gmprocess/io/waveqlab3d/core.py
Still need to verify (1) ordering of values in fake data files matches
simulation output and (2) geometry and topology information matches
desired ordering.
I added the "congif=none" on the core.py file within waveqlab3d. This cleared up all the fails on my local.
> Add waveqlab3d reader and corresponding test data.

- gmprocess/data/config_production.yml
- gmprocess/data/config_test.yml
- gmprocess/data/testdata/conf_small.yml
- gmprocess/data/testdata/config_min_freq_0p2.yml
- gmprocess/waveform_processing/processing.py
- tests/gmprocess/io/obspy/obspy_test.py
- tests/gmprocess/waveform_processing/lowpass_max_test.py
Add options to instrument response removal to allow for no water level and/or no pre filter. Closes #961. 
NOTE: This will require all users to update their config file in the instrument response section to add the new `pre_filt` key:
```yml
- remove_response:
pre_filt: True
f1: 0.001
f2: 0.005
f3: Null
f4: Null
water_level: 60.0
```
> Extend remove instrument response options

- gmprocess/waveform_processing/phase.py
- tests/gmprocess/core/streamcollection_test.py
scipy is now using *hann*, instead of *hanning*, for the window name. Specify this window explicitly.
> Fix tests to use explicit hann window with obspy.

- doc_source/contents/developer/changelog.md
- src/gmprocess/apps/gmrecords.py
- src/gmprocess/io/asdf/stream_workspace.py
- src/gmprocess/io/obspy/fdsn_fetcher.py
- src/gmprocess/io/report.py
- src/gmprocess/subcommands/base.py
- src/gmprocess/subcommands/config.py
- src/gmprocess/subcommands/export_failure_tables.py
- src/gmprocess/subcommands/process_waveforms.py
- src/gmprocess/utils/assemble_utils.py
- src/gmprocess/utils/config.py
Added the "config" subcommand that has options to save the config in the workspace files to a file for review, and also to update the config in the workspace file with the config options that are currently specified in the projects's conf directory. This is intended to help users that have older workspace files that have config options in them that are no longer compatible with the current version of the code. Be careful when running the update, though, to be sure that any customizations are reflected by the project's config file.
> Add config subcommand

- doc_source/contents/tutorials/lme.md
- docs/contents/tutorials/lme.html
1. Only the edited Markdown file and the associated HTML file are included in the PR. I did not include any other HTML files.
2. I changed the formatting the Markdown file so that each sentence is on its own line. In the long-term this makes the commits and history of changes cleaner. I suggest we adopt this practice. It has no affect on the generated documentation.
> DOCS: Fix some typos (misspellings) in the Linear Mixed Effects tutorial

- src/gmprocess/subcommands/assemble.py
- src/gmprocess/utils/assemble_utils.py
- src/gmprocess/utils/base_utils.py
- src/gmprocess/utils/misc.py
* Remove redundant retrieval of event information from ComCat in the gmrecords assemble subcommand.
* Migrate some use of `os.path` to `pathlib` methods.
Closes #1030
> Remove redundant retrieval of event information from ComCat.

- src/gmprocess/apps/gmrecords.py
- src/gmprocess/subcommands/assemble.py
- The projects path was being handed off to `get_config` in `GMrecordsApp` which meant that none of the project-specific configs were being found and so they were not getting used. 
- When assemble fails, the `_assemble_event` method returns the event object rather than the workspace file name, which caused an error when `_summarize_files_created` is called, rather than exiting gracefully.
> Bugfix on config path

- doc_source/contents/developer/changelog.md
- src/gmprocess/core/stationtrace.py
- src/gmprocess/io/obspy/core.py
- tests/gmprocess/io/obspy/obspy_test.py
Closes #992
- Moves the application of the conversion to the `read_obspy` module; this was in the `StationTrace` init method and was the reason for the bug since it is called both when the data is read in and then also when the data is retrieved from the HDF file. 
- Added a unit test for CSN SAC data; confirmed that the resulting values give similar results to a nearby permanent station.
> Fixed sac units conversion issue

- src/gmprocess/io/global_fetcher.py
Pattern matching in find_fetchers for dynamically importing all fetchers fails in some install situations. This should make it more robust.
> Fix pattern match in find_fetcher

- src/gmprocess/waveform_processing/adjust_highpass_ridder.py
- src/gmprocess/waveform_processing/corner_frequencies.py
This fixes a bug that can come up when an individual trace has failed qa checks and so it didn't find corner frequencies. We just need to always check that individual traces have passed before looking for attributes like this.
> Fix Ridder loop to work when any_trace_failures is False
